#ifndef AGVFORKPARAM_H
#define AGVFORKPARAM_H
#include"./typeDefines.h"

const int32 AGV_FORK_TURN_DIRECTION_LEFT = 1;
const int32 AGV_FORK_TURN_DIRECTION_RIGHT = 2;
const int32 AGV_FORK_TRUN_DIRECTION_STOPTURN = 3;
const int32 AGV_FORK_TURN_NONE = 3; //not turn, move straight

const int32 AGV_FORK_MOVE_STOPMOVE = 0;
const int32 AGV_FORK_MOVE_FORWARD = 1;
const int32 AGV_FORK_MOVE_BACKWARD = 2;
const int32 AGV_FORK_MOVE_SIDEWARD = 3;
const int32 AGV_FORK_MOVE_ROUNDWARD = 4; //self rotate

const int32 AGV_FORK_START_POINT_VELOCITY_ACCELERATE = 1;
const int32 AGV_FORK_START_POINT_VELOCITY_CONSTSPEED = 2;
const int32 AGV_FORK_END_POINT_VELOCITY_DECELERATE = 1;
const int32 AGV_FORK_END_POINT_VELOCITY_CONSTSPEED = 2;
const int32 AGV_FORK_END_POINT_VELOCITY_DEFAULT = AGV_FORK_END_POINT_VELOCITY_CONSTSPEED;

const int32 AGV_FORK_ACTION_LOCK = 1;
const int32 AGV_FORK_ACTION_NONE_LOCK = 2;
//const int32 AGV_FORK_ACTION_UP_ADJUST = 3;
//const int32 AGV_FORK_ACTION_DOWN_ADJUST = 4;
const int32 AGV_FORK_LOCK_UP = 6;
const int32 AGV_FORK_LOCK_DOWN = 6;

const int32 AGV_FORK_WORK_TYPE_NONE = 0;
const int32 AGV_FORK_WORK_TYPE_LOAD_GOODS = 1;
const int32 AGV_FORK_WORK_TYPE_UNLOAD_GOODS  = 2;

const int32 AGV_FORK_MOVE_OUT_HEAD = 1;
const int32 AGV_FORK_MOVE_OUT_TAIL = 2;

const int32 AGV_FORK_MOVE_IN_HEAD = 3;
const int32 AGV_FORK_MOVE_IN_TAIL = 4;


#endif // AGVFORKPARAM_H
